spring:
  flyway:
    enabled: true
  datasource:
    druid:
      url: jdbc:h2:mem:test-exam?useUnicode=true&characterEncoding=UTF-8&useSSL=false
      username: root
      password: root
  banner:
    location: banner.txt
server:
  servlet:
    context-path: /test-exam

mybatis-plus:
  mapper-locations: classpath:/mapper/*Mapper.xml
  check-config-location: true
  configuration:
    # Mybatis一级缓存，默认为 SESSION。
    # SESSION session级别缓存，同一个session相同查询语句不会再次查询数据库
    # STATEMENT 关闭一级缓存
    # 单服务架构中（有且仅有只有一个程序提供相同服务），一级缓存开启不会影响业务，只会提高性能。 微服务架构中需要关闭一级缓存，原因：Service1先查询数据，若之后Service2修改了数据，之后Service1又再次以同样的查询条件查询数据，因走缓存会出现查处的数据不是最新数据
    local-cache-scope: statement
    # 开启Mybatis二级缓存，默认为 true。
    cache-enabled: false
    # 是否开启自动驼峰命名规则（camel case）映射，即从经典数据库列名 A_COLUMN（下划线命名） 到经典 Java 属性名 aColumn（驼峰命名） 的类似映射。
    # 默认值：true
    # 此属性在 MyBatis 中原默认值为 false，在 MyBatis-Plus 中，此属性也将用于生成最终的 SQL 的 select body
    # 如果您的数据库命名符合规则无需使用 @TableField 注解指定数据库字段名
    map-underscore-to-camel-case: true
  global-config:
    db-config:
      # 全局默认主键类型
      id-type: auto

